### ISSUE TITLE
Landmark Hotel Association

### ISSUE THREAD

**Issue by MarkoKovac153** [OllieWebb/Hotel#2]
As a Customer,
When I search a landmark,
I am shown local Hotels,
so that I can book somewhere around the landmark

**Comment by Eve-Burton** [comment]
Gherkin
 Feature: Searching for Landmarks and Local Hotels

  Scenario: Show local Hotels when searching for a Landmark
    Given I am a customer
    When I search for a landmark with the name "Eiffel Tower"
    Then I should be shown a list of local hotels
