### ISSUE TITLE
Availability Checks

### ISSUE THREAD

**Issue by MarkoKovac153** [OllieWebb/Hotel#3]
As a Customer,
When I request data on a hotel
I want to see if the hotel is available,
So that I can book a hotel

**Comment by Eve-Burton** [comment]
Gherkin 

Feature: Checking Hotel Availability

  Scenario: Check if a Hotel is available for booking
    Given I am a customer
    When I request data on a hotel with the name "Grand Hotel"
    Then I want to see if the hotel is available
    So that I can book the hotel

**Comment by stevrnd** [comment]
using booking.com to scrape data for availability and check for edge cases
