### ISSUE TITLE
Booking Insights

### ISSUE THREAD

**Issue by MarkoKovac153** [OllieWebb/Hotel#4]
As a Customer,
When I request data on a hotel,
I am given insights into that hotel,
To help me with my booking

**Comment by Eve-Burton** [comment]
Feature: Providing Hotel Insights

  Scenario: Provide insights into a Hotel to help with booking
    Given I am a customer
    When I request data on a hotel with the name "Grand Hotel"
    Then I should be given insights into that hotel
    And these insights should help me with my booking
