### ISSUE TITLE
User Reviews

### ISSUE THREAD

**Issue by MarkoKovac153** [OllieWebb/Hotel#5]
As a Customer,
When I want to look at reviews for a hotel,
I can see them and add to them,
So that I can add my reviews and ratings and see others

**Comment by Eve-Burton** [comment]
Gherkin 
Feature: Viewing and Adding Hotel Reviews

  Scenario: View and add reviews for a Hotel
    Given I am a customer
    When I want to look at reviews for a hotel with the name "Grand Hotel"
    Then I can see the existing reviews
    And I can add my own review and rating
    So that I can contribute my experience and see others' experiences
